spring:
  application:
    name: demo

  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://admin:password123@localhost:27017/documents_db?authSource=admin}

  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}
    socket-timeout: 10s

server:
  error:
    include-message: always